name: Check Changed Files

on:
  push:
    branches:
      - main

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: List Changed Files
        run: |
          echo"last modified files"
          git diff --name-only HEAD^ HEAD
          
