name: Check Changed Files

on:
  push:
    branches:
      - main

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: List Changed Files
        run: |
          echo "last modified files 1"
          git diff --name-only
          echo "last modified files 2"
          git diff --name-only HEAD^2
          echo "last modified files 3"
          git diff --name-only HEAD
          
          
