name: Print Modified Files

on:
  push:
    branches:
      - main

jobs:
  print_modified_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List modified files
        run: |
          git diff --name-only main

